services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "127.0.0.1:8000:8000" # Only accessible from this computer
    env_file:
      - .env
    volumes:
      - ./backend:/app:ro   # <-- Mount local backend code, Added :ro to make it read-only
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
      

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "127.0.0.1:8501:8501" # Only accessible from this computer
    env_file:
      - .env
    volumes:
      - ./frontend:/app:ro  # <-- Mount local frontend code, Added :ro to make it read-only
    command: >
      streamlit run app.py --server.port=8501 --server.address=0.0.0.0